# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TodayHotRecruit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodayHotRecruit

#    pod 'YTKNetwork'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'SDAutoLayout'
    pod 'MBProgressHUD'

  target 'TodayHotRecruitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodayHotRecruitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
